# Site settings
title: plwonks
email: pl-wonks-l@list.iu.edu
description: > # this means to ignore newlines until "baseurl:"
  Programming language enthusiasts from Indiana University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wonks.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-paginate
paginate_path: "/talks/page:num/"

# Build settings
markdown: kramdown
future : true # so that pages in the future get built; doesn't work :/
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

paginate: 10
